language: php

php:
    - 5.6
    - 7.0
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer selfupdate

install: composer update --prefer-dist --no-interaction --optimize-autoloader

script: phpunit --exclude-group infra
