---

#######
# Dir #
#######

manala_deploy_dir: /srv/app

############
# Releases #
############

manala_deploy_releases: 5

############
# Strategy #
############

manala_deploy_strategy: git

manala_deploy_strategy_git_repo:    "{{ lookup('pipe','git ls-remote --get-url origin') }}"
manala_deploy_strategy_git_version: master

##########
# Copied #
##########

manala_deploy_copied:
  - vendor
  - node_modules

##########
# Shared #
##########

manala_deploy_shared_files:
  - app/config/parameters.yml

manala_deploy_shared_dirs:
  - var/logs

############
# Writable #
############

manala_deploy_writable_dirs_mode: ug=rwx,o=rx
manala_deploy_writable_dirs:
  - var/cache
  - var/logs
